### PR TITLE
Test spring restful

### PR DESCRIPTION
**Pull request by yuqisun**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yuqisun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=55)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=55) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by dsyer** [comment]
The main point of the "initial" project is to be empty (except for a build system). I think this PR is maybe a mistake?

**Comment by yuqisun** [comment]
really sorry, my mistake ...

**Comment by dsyer** [comment]
No worries.

**Pull request closed without merging**
