### PR TITLE
Remove jsonpath dependency which it's unnecessary since the newer versions use Jackon by default

### PR DESCRIPTION
**Pull request by veronx**
By merging this commit the Adding a JSON Library part will be removed. The idea is to make the article as simple as possible for beginners.

### CODE REVIEW

**Comment by Buzzardo** [comment]
Shouldn't pom.xml and build.gradle be updated as well?

**Comment by veronx** [comment]
> Shouldn't pom.xml and build.gradle be updated as well?

You are right. Just updated them on 'complete'

**Comment by Buzzardo** [comment]
Thanks. :)

**Comment by veronx** [comment]
> Thanks. :)

I am glad to help :)

**Pull request merged**
