### PR TITLE
Correct formatting on resulting message description

### PR DESCRIPTION
**Pull request by ManaLocked**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Music-Man94 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=86)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=86) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
PR looks great. Sign our CLA and I’ll merge your patch.

**Comment by pivotal-issuemaster** [comment]
@ManaLocked Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=86)!

**Comment by ManaLocked** [comment]
@gregturn Thanks for the feedback! The CLA is signed.

**Pull request merged**
