### PR TITLE
doc: Use single quotes in build.gradle

### PR DESCRIPTION
**Pull request by serv-inc**
as recommended in https://guides.gradle.org/style-guide/#favor_single_quotes_for_plain_strings_in_build_script_listings.

This also makes `echo "..." > build.gradle` copy-pasting possible.

PS: thanks for the awesomely helpful tutorial

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@serv-inc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=96)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=96) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@serv-inc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-rest-service&pullRequestId=96)!

**Comment by ksundong** [comment]
In my opinion, it would be better to change another build.gradle files.
e.g.) `initial/build.gradle`

**Comment by Buzzardo** [comment]
Please add that to the /initial part of the project (/initial/build.gradle), too. Thanks.

**Comment by serv-inc** [comment]
@ksundong @Buzzardo: done

**Comment by dsyer** [comment]
#99 will supersede this PR. Thanks for the effort.

**Comment by dsyer** [comment]
Closed with #99

**Pull request closed without merging**
